name: Cypress Test Manual

on:
  workflow_dispatch:
    inputs:
      execution:
        description: 'Digite a feature que deseja executar'
        required: true
        default: 'Orange.feature'
        options:
          - Contact_Us.feature
          - Orange.feature
          - Saucelabs.feature
          - ScanSource.feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout projeto
      uses: actions/checkout@v2

    - name: Configurar o Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 

    - name: Instalar dependências
      run: npm install --force

    - name: Executar testes Cypress
      run: npx cypress run --spec "cypress/e2e/features/${{ inputs.execution }}"

    - name: verificar diretorio
      run: ls

    - name: Publicar resultados dos testes
      uses: actions/upload-artifact@v2
      with:
        name: cypress-results
        path: cypress/screenshots
